version: '3'
services:
  ros2_node:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_IMAGE=ros2img
    image: ros2img:latest
    container_name: ros2-container
    volumes:
      - ./ros2_ws:/root/ros2_ws
      - /proc:/root/proc
    # restart: always